# action名称
name: Publish and Release

# 当代码合并到master分支的时候，执行下列脚本
on:
  push:
    branches: [main]

# 任务
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Use a specific version

      - name: 设置Node.js
        uses: actions/setup-node@v3 # Use a specific version
        with:
          node-version: "20.x"

      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          publish_dir: ./dist # Fix typo
          github_token: ${{ secrets.CICD }}
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: 自动部署
